export default{
    DETAIL_LIST:"DETAIL_LIST",
    DETAIL_TIPC:"DETAIL_TIPC",
    DETAIL_SUPPORT:"DETAIL_SUPPORT",
    DETAIL_VENUD:"DETAIL_VENUD",
    DETAIL_CITY:"DETAIL_CITY",
    DETAIL_TIME:"DETAIL_TIME",
    SHOW_NOTICE:"SHOW_NOTICE",
    DETAIL_REC:"DETAIL_REC"
}